name: Test Scoop Bucket

on: [push]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test Scoop Bucket
        run: |
          # Install Scoop
          Set-ExecutionPolicy RemoteSigned -Scope CurrentUser
          iex "& {$(irm get.scoop.sh)} -RunAsAdmin"
          # Install the app from your bucket
          scoop bucket add my-scoop-bucket https://github.com/mcserverhosting-net/scoop.git
          scoop install mcsh
          # Run any tests for the app
          mcsh version --client=true